INSERT INTO elo('eloNum', 'elo') VALUES(0, 'Unranked');
INSERT INTO elo('eloNum', 'elo') VALUES(1, 'Iron 4');
INSERT INTO elo('eloNum', 'elo') VALUES(2, 'Iron 3');
INSERT INTO elo('eloNum', 'elo') VALUES(3, 'Iron 2');
INSERT INTO elo('eloNum', 'elo') VALUES(4, 'Iron 1');
INSERT INTO elo('eloNum', 'elo') VALUES(5, 'Silver 4');
INSERT INTO elo('eloNum', 'elo') VALUES(6, 'Silver 3');
INSERT INTO elo('eloNum', 'elo') VALUES(7, 'Silver 2');
INSERT INTO elo('eloNum', 'elo') VALUES(8, 'Silver 1'); 
INSERT INTO elo('eloNum', 'elo') VALUES(9, 'Gold 4');
INSERT INTO elo('eloNum', 'elo') VALUES(10, 'Gold 3');
INSERT INTO elo('eloNum', 'elo') VALUES(11, 'Gold 2');
INSERT INTO elo('eloNum', 'elo') VALUES(12, 'Gold 1'); 
INSERT INTO elo('eloNum', 'elo') VALUES(13, 'Platinum 4');
INSERT INTO elo('eloNum', 'elo') VALUES(14, 'Platinum 3');
INSERT INTO elo('eloNum', 'elo') VALUES(15, 'Platinum 2');
INSERT INTO elo('eloNum', 'elo') VALUES(16, 'Platinum 1'); 
INSERT INTO elo('eloNum', 'elo') VALUES(17, 'Diamond 4');
INSERT INTO elo('eloNum', 'elo') VALUES(18, 'Diamond 3');
INSERT INTO elo('eloNum', 'elo') VALUES(19, 'Diamond 2');
INSERT INTO elo('eloNum', 'elo') VALUES(20, 'Diamond 1'); 
INSERT INTO elo('eloNum', 'elo') VALUES(21, 'Master');
INSERT INTO elo('eloNum', 'elo') VALUES(22, 'Grandmaster');  
INSERT INTO elo('eloNum', 'elo') VALUES(23, 'Challenger'); 